---
- name: Update system
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true
    autoremove: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if needed
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to package upgrades"
  when: reboot_required.stat.exists
